import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import AuroraBackground from "@/components/main/AuroraBackground";
import Footer from "@/components/main/Footer";
import Header from "@/components/main/Header";
import {SITE, SITE_KEYWORDS} from "@/constants/site";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  // Resolves all relative metadata URLs (og:image, canonical) against the site origin.
  metadataBase: new URL(SITE.url),
  title: {
    default: SITE.title,
    template: `%s | ${SITE.name}`,
  },
  description: SITE.description,
  applicationName: SITE.name,
  authors: [{name: SITE.name, url: SITE.url}],
  creator: SITE.name,
  publisher: SITE.name,
  keywords: SITE_KEYWORDS,
  category: "technology",
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: SITE.locale,
    url: SITE.url,
    siteName: SITE.name,
    title: SITE.title,
    description: SITE.description,
    // og image is generated by app/opengraph-image.tsx and picked up automatically.
  },
  twitter: {
    card: "summary_large_image",
    title: SITE.title,
    description: SITE.description,
    creator: "@AdibHoque",
  },
  icons: {
    icon: "/favicon.ico",
  },
  // Google Search Console is already verified (you added the property), so no
  // meta-tag verification is needed here. If you ever re-verify via the HTML-tag
  // method, add: verification: { google: "<token>" }.
};

// Person + WebSite structured data. This is the single biggest lever for ranking
// as the "Adib Hoque" entity: it tells Google exactly who this page is about,
// which real profiles (`sameAs`) belong to the same person, and what they do.
function StructuredData() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Person",
        "@id": `${SITE.url}/#person`,
        name: SITE.name,
        url: SITE.url,
        image: `${SITE.url}/opengraph-image`,
        jobTitle: SITE.jobTitle,
        description: SITE.description,
        email: `mailto:${SITE.email}`,
        sameAs: Object.values(SITE.socials),
        knowsAbout: SITE.knowsAbout,
      },
      {
        "@type": "WebSite",
        "@id": `${SITE.url}/#website`,
        url: SITE.url,
        name: SITE.title,
        description: SITE.description,
        inLanguage: "en",
        publisher: {"@id": `${SITE.url}/#person`},
        about: {"@id": `${SITE.url}/#person`},
      },
    ],
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{__html: JSON.stringify(jsonLd)}}
    />
  );
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-bg text-text overflow-y-scroll overflow-x-hidden`}
      >
        <StructuredData />
        <AuroraBackground />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
